#端口号
server:
  port: 8762
spring:
  application:
    name: /eurekaServer #应用名称
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://182.92.110.208:8762/eureka/
