server:
  port: 8762 #端口号
eureka:
  client:
    #registerWithEureka: false #是否注册自身到eureka服务器  默认为true
    #fetchRegistry: false #是否从eureka服务器获取注册信息 默认为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/${spring.application.name}/,http://${eureka.instance.hostname}:8763/${spring.application.name}/
