server:
  port: 8761 #端口号
eureka:
  client:
    registerWithEureka: true #是否注册自身到eureka服务器  默认为true 是
    fetchRegistry: true #是否从eureka服务器获取注册信息 默认为true 是
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/${spring.application.name}/,http://${eureka.instance.hostname}:8763/${spring.application.name}/
